spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: whanau.gda@gmail.com
    password: 19az25g07d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
